language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - pypy
  - pypy3
install:
  - pip install coverage
  - git config --global user.name "Jenkins CI"
script:
  - coverage run --source=gitversion tests.py
  - coverage report --show-missing
